=== ThePitM4ster/MisGustos/XML/conciertos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="conciertos">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="concierto"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="concierto">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Nombre"/>
                <xs:element ref="Año"/>
                <xs:element ref="Aforo"/>
                <xs:element ref="Lugar"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Nombre" type="xs:string"/>
    <xs:element name="Año" type="xs:integer"/>
    <xs:element name="Aforo" type="xs:decimal"/>
    <xs:element name="Lugar" type="xs:string"/>
</xs:schema>

=== ThePitM4ster/MisGustos/XML/conciertos.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="conciertos.xsl"?>
<conciertos  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="conciertos.xsd">
    <concierto>
        <Nombre>Toronto SARS Benefit</Nombre>
        <Año>2003</Año>
        <Aforo>450.000</Aforo>
        <Lugar>Toronto</Lugar>
    </concierto>
    <concierto>
        <Nombre>Rolling Stones</Nombre>
        <Año>2016</Año>
        <Aforo>500.000</Aforo>
        <Lugar>La Habana</Lugar>
    </concierto>
    <concierto>
        <Nombre>Simon y Garfunkel</Nombre>
        <Año>1981</Año>
        <Aforo>500.000</Aforo>
        <Lugar>Central Park.NY</Lugar>
    </concierto>
    <concierto>
        <Nombre>Summer Jam</Nombre>
        <Año>1973</Año>
        <Aforo>600.000</Aforo>
        <Lugar>Watkins Glen</Lugar>
    </concierto>
    <concierto>
        <Nombre>Toronto SARS Benefit</Nombre>
        <Año>2003</Año>
        <Aforo>450.000</Aforo>
        <Lugar>Toronto</Lugar>
    </concierto>
    <concierto>
        <Nombre>Rolling Stones</Nombre>
        <Año>2016</Año>
        <Aforo>500.000</Aforo>
        <Lugar>La Habana</Lugar>
    </concierto>
    <concierto>
        <Nombre>Simon y Garfunkel</Nombre>
        <Año>1981</Año>
        <Aforo>500.000</Aforo>
        <Lugar>Central Park.NY</Lugar>
    </concierto>
    <concierto>
        <Nombre>Summer Jam</Nombre>
        <Año>1973</Año>
        <Aforo>600.000</Aforo>
        <Lugar>Watkins Glen</Lugar>
    </concierto>
    <concierto>
        <Nombre>Toronto SARS Benefit</Nombre>
        <Año>2003</Año>
        <Aforo>450.000</Aforo>
        <Lugar>Toronto</Lugar>
    </concierto>
    <concierto>
        <Nombre>Rolling Stones</Nombre>
        <Año>2016</Año>
        <Aforo>500.000</Aforo>
        <Lugar>La Habana</Lugar>
    </concierto>
    <concierto>
        <Nombre>Simon y Garfunkel</Nombre>
        <Año>1981</Año>
        <Aforo>500.000</Aforo>
        <Lugar>Central Park.NY</Lugar>
    </concierto>
    <concierto>
        <Nombre>Summer Jam</Nombre>
        <Año>1973</Año>
        <Aforo>600.000</Aforo>
        <Lugar>Watkins Glen</Lugar>
    </concierto>
    <concierto>
        <Nombre>Toronto SARS Benefit</Nombre>
        <Año>2003</Año>
        <Aforo>450.000</Aforo>
        <Lugar>Toronto</Lugar>
    </concierto>
    <concierto>
        <Nombre>Rolling Stones</Nombre>
        <Año>2016</Año>
        <Aforo>500.000</Aforo>
        <Lugar>La Habana</Lugar>
    </concierto>
    <concierto>
        <Nombre>Simon y Garfunkel</Nombre>
        <Año>1981</Año>
        <Aforo>500.000</Aforo>
        <Lugar>Central Park.NY</Lugar>
    </concierto>
    <concierto>
        <Nombre>Summer Jam</Nombre>
        <Año>1973</Año>
        <Aforo>600.000</Aforo>
        <Lugar>Watkins Glen</Lugar>
    </concierto>
    <concierto>
        <Nombre>Toronto SARS Benefit</Nombre>
        <Año>2003</Año>
        <Aforo>450.000</Aforo>
        <Lugar>Toronto</Lugar>
    </concierto>
    <concierto>
        <Nombre>Rolling Stones</Nombre>
        <Año>2016</Año>
        <Aforo>500.000</Aforo>
        <Lugar>La Habana</Lugar>
    </concierto>
    <concierto>
        <Nombre>Simon y Garfunkel</Nombre>
        <Año>1981</Año>
        <Aforo>500.000</Aforo>
        <Lugar>Central Park.NY</Lugar>
    </concierto>
    <concierto>
        <Nombre>Summer Jam</Nombre>
        <Año>1973</Año>
        <Aforo>600.000</Aforo>
        <Lugar>Watkins Glen</Lugar>
    </concierto>
</conciertos>
